version: '3.8'

services:
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - Code_Sync
    ports:
      - "3000:3000"
    command: npm run dev

  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - Code_Sync
    ports:
      - "5173:5173"
    depends_on:
      - backend
    command: npm run dev -- --host

networks:
  Code_Sync:
    driver: bridge
